#! /bin/bash
# (c) by it-eddy
# https://github.com/it-eddy/new_system_setup/



# check arguments
if [ -z "$1" ]; then
    echo "Usage: $0 <IPv6 address>"
    exit 1
fi

ip -6 neigh show | grep "$1 dev " | grep -v 'FAILED' | cut -d' ' -f5 | sort | uniq
